export const PREDEFINED_SKILLS = [
  // Programming Languages
  'Python',
  'JavaScript',
  'TypeScript',
  'Java',
  'C',
  'C#',
  'C++',
  'Go',
  'Rust',
  'Ruby',
  'PHP',
  'Swift',
  'Kotlin',
  'Scala',
  'Perl',
  'Haskell',
  'Elixir',
  'Clojure',
  'R',
  'MATLAB',
  'Groovy',
  'Lua',
  'Shell Scripting',
  'Bash',
  'PowerShell',
  'VB.Net',
  'Objective-C',
  'Dart',
  'Solidity',
  'Assembly',
  'SQL',
  'PL/SQL',
  'T-SQL',

  // Frontend Frameworks & Libraries
  'React',
  'Vue.js',
  'Angular',
  'Svelte',
  'Next JS',
  'Nuxt JS',
  'Remix',
  'Astro',
  'Gatsby',
  'Ember.js',
  'Backbone.js',
  'Preact',
  'Alpine.js',
  'HTMX',
  'Qwik',
  'Solid.js',

  // Backend Frameworks
  'Node.js',
  'Express',
  'Django',
  'Flask',
  'FastAPI',
  'Spring Boot',
  'Spring Framework',
  'Laravel',
  'Symfony',
  'Ruby on Rails',
  'ASP.NET',
  'ASP.NET Core',
  '.NET',
  'Gin',
  'Echo',
  'Fiber',
  'Actix',
  'Rocket',
  'Phoenix',
  'Nest.js',
  'Koa',
  'Hapi',
  'Fastify',
  'Strapi',
  'Loopback',
  'Sails.js',

  // Mobile Development
  'React Native',
  'Flutter',
  'Ionic',
  'Xamarin',
  'NativeScript',
  'Cordova',
  'Progressive Web Apps',
  'PWA',

  // Styling & UI
  'Tailwind CSS',
  'Bootstrap',
  'Material UI',
  'Chakra UI',
  'Ant Design',
  'Styled Components',
  'CSS-in-JS',
  'SASS',
  'LESS',
  'PostCSS',
  'Emotion',
  'Radix UI',
  'shadcn/ui',
  'Headless UI',
  'Framer Motion',
  'Three.js',
  'Babylon.js',
  'Cesium.js',

  // State Management
  'Redux',
  'Zustand',
  'Jotai',
  'Recoil',
  'MobX',
  'Context API',
  'Vuex',
  'Pinia',
  'NgRx',
  'Akita',

  // Testing
  'Jest',
  'Vitest',
  'Mocha',
  'Chai',
  'Jasmine',
  'Cypress',
  'Playwright',
  'Selenium',
  'Puppeteer',
  'React Testing Library',
  'Enzyme',
  'Testing Library',
  'Unit Testing',
  'Integration Testing',
  'E2E Testing',
  'TDD',
  'BDD',

  // Databases
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Firebase',
  'Supabase',
  'DynamoDB',
  'Cassandra',
  'Redis',
  'Elasticsearch',
  'Neo4j',
  'CouchDB',
  'RethinkDB',
  'SQLite',
  'MariaDB',
  'Oracle Database',
  'SQL Server',
  'Memcached',
  'Prisma',
  'TypeORM',
  'Sequelize',
  'SQLAlchemy',
  'Hibernate',
  'Mongoose',
  'Realm',

  // Cloud Platforms
  'AWS',
  'Amazon EC2',
  'Amazon S3',
  'AWS Lambda',
  'AWS RDS',
  'AWS DynamoDB',
  'AWS CloudFront',
  'AWS API Gateway',
  'Google Cloud Platform',
  'Google Cloud Storage',
  'Google Cloud Functions',
  'Google Cloud SQL',
  'Google Cloud Pub/Sub',
  'Microsoft Azure',
  'Azure App Service',
  'Azure SQL Database',
  'Azure Cosmos DB',
  'Azure Functions',
  'Azure DevOps',
  'Heroku',
  'DigitalOcean',
  'Linode',
  'Vercel',
  'Netlify',
  'Railway',
  'Render',
  'Fly.io',

  // DevOps & Infrastructure
  'Docker',
  'Docker Compose',
  'Kubernetes',
  'Helm',
  'Terraform',
  'Ansible',
  'Jenkins',
  'GitLab CI/CD',
  'GitHub Actions',
  'CircleCI',
  'Travis CI',
  'ArgoCD',
  'Prometheus',
  'Grafana',
  'ELK Stack',
  'Elasticsearch',
  'Logstash',
  'Kibana',
  'Datadog',
  'New Relic',
  'Sentry',
  'CloudFlare',
  'Nginx',
  'Apache',
  'HAProxy',
  'Load Balancing',
  'Virtualization',
  'VirtualBox',
  'VMware',
  'Vagrant',

  // Message Queues & Event Streaming
  'Kafka',
  'RabbitMQ',
  'Apache ActiveMQ',
  'AWS SQS',
  'AWS SNS',
  'Google Pub/Sub',
  'Azure Service Bus',
  'Redis Streams',
  'NATS',
  'ZeroMQ',

  // Search & Analytics
  'Elasticsearch',
  'Solr',
  'Algolia',
  'Meilisearch',
  'Typesense',
  'Google Analytics',
  'Mixpanel',
  'Amplitude',
  'Segment',
  'Tableau',
  'Power BI',
  'Looker',
  'Metabase',

  // API & Integration
  'REST API',
  'GraphQL',
  'Apollo',
  'Relay',
  'gRPC',
  'WebSocket',
  'OAuth 2.0',
  'JWT',
  'API Gateway',
  'Postman',
  'Insomnia',
  'Swagger',
  'OpenAPI',
  'Zapier',
  'IFTTT',
  'Webhooks',

  // Data Science & ML
  'Machine Learning',
  'Deep Learning',
  'TensorFlow',
  'PyTorch',
  'Keras',
  'Scikit-learn',
  'NumPy',
  'Pandas',
  'Matplotlib',
  'Seaborn',
  'Plotly',
  'OpenCV',
  'NLTK',
  'spaCy',
  'Hugging Face',
  'LLM',
  'Generative AI',
  'GenAI',
  'LangChain',
  'LangGraph',
  'LangSmith',
  'OpenAI API',
  'Claude API',
  'Pinecone',
  'Weaviate',
  'Milvus',
  'Chroma',
  'Vector Database',
  'RAG',
  'Fine-tuning',

  // Version Control
  'Git',
  'Git and Github',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'Gitea',
  'Mercurial',
  'SVN',

  // Code Quality & Linting
  'ESLint',
  'Prettier',
  'SonarQube',
  'Pylint',
  'Flake8',
  'Black',
  'RuboCop',
  'Checkstyle',
  'StyleLint',
  'Husky',
  'Pre-commit Hooks',

  // Build Tools & Package Managers
  'Webpack',
  'Vite',
  'Parcel',
  'Rollup',
  'Esbuild',
  'Turbopack',
  'npm',
  'yarn',
  'pnpm',
  'Turborepo',
  'Lerna',
  'Maven',
  'Gradle',
  'Cargo',
  'pip',
  'Poetry',
  'Composer',
  'Bundler',

  // Documentation
  'Storybook',
  'Docusaurus',
  'MkDocs',
  'Sphinx',
  'Swagger',
  'OpenAPI',
  'Javadoc',
  'JSDoc',
  'TypeDoc',
  'Documentation Writing',

  // Design Tools
  'Figma',
  'Adobe XD',
  'Sketch',
  'InVision',
  'Framer',
  'Webflow',
  'Canva',
  'Photoshop',
  'Illustrator',
  'Adobe Creative Suite',
  'Graphic Design',
  'UI/UX',
  'Wireframing',
  'Prototyping',

  // Project Management
  'Jira',
  'Asana',
  'Monday.com',
  'Trello',
  'Notion',
  'Confluence',
  'Linear',
  'GitHub Projects',
  'Azure DevOps',
  'Agile Methodologies',
  'Scrum',
  'Kanban',
  'Lean',

  // Monitoring & Logging
  'Prometheus',
  'Grafana',
  'Jaeger',
  'Datadog',
  'New Relic',
  'Sentry',
  'LogRocket',
  'Splunk',
  'Sumo Logic',
  'Papertrail',
  'CloudWatch',
  'Stack Driver',

  // Soft Skills
  'Communication Skills',
  'Leadership',
  'Team Management',
  'Problem Solving',
  'Critical Thinking',
  'Creativity',
  'Time Management',
  'Project Management',
  'Presentation Skills',
  'Public Speaking',
  'Written Communication',
  'Verbal/nonverbal communication',
  'Interpersonal communication',
  'Collaboration',
  'Adaptability',
  'Attention to Detail',
  'Delegation',
  'Delegating tasks',
  'Mentoring',
  'Coaching',
  'Negotiation',
  'Conflict Resolution',
  'Emotional Intelligence',
  'Openness',
  'People skills',
  'Customer Service',
  'Empathy',

  // Business & Soft Skills
  'Product Management',
  'Business Analysis',
  'Entrepreneurship',
  'Strategic Planning',
  'Market Research',
  'Competitive Analysis',
  'Business Development',
  'Sales',
  'Marketing',
  'Email Marketing',
  'SEO/SEM marketing',
  'Social Media',
  'Content Marketing',
  'Brand Management',
  'Financial Analysis',
  'Data Analysis',
  'Research',

  // Architecture & Design Patterns
  'Microservices',
  'Monolithic Architecture',
  'Event-Driven Architecture',
  'Distributed Systems',
  'System Design',
  'Design Patterns',
  'SOLID Principles',
  'Clean Code',
  'Refactoring',
  'Domain-Driven Design',
  'CQRS',
  'Event Sourcing',

  // Security
  'Security',
  'Cybersecurity',
  'Application Security',
  'Network Security',
  'Encryption',
  'SSL/TLS',
  'OWASP',
  'Penetration Testing',
  'Security Auditing',
  'Authentication',
  'Authorization',
  'OAuth 2.0',
  'JWT',
  'SAML',
  'Two-Factor Authentication',

  // Operating Systems
  'Linux',
  'Windows',
  'macOS',
  'Ubuntu',
  'CentOS',
  'RedHat Linux 7.5',
  'Debian',
  'Alpine',
  'UNIX',
  'iOS',
  'Android',

  // Miscellaneous
  'Concurrency',
  'Parallelism',
  'Performance Optimization',
  'Caching Strategies',
  'Database Optimization',
  'Query Optimization',
  'Load Balancing',
  'Scalability',
  'High Availability',
  'Disaster Recovery',
  'Backup & Recovery',
  'Compliance',
  'GDPR',
  'HIPAA',
  'SOC 2',
  'ISO 27001',
  'Accessibility',
  'WCAG',
  'Internationalization',
  'Localization',
  'i18n',
  'l10n',
  'Excel',
  'Microsoft Office',
  'Spreadsheet',
  'Makefiles',
  'Concurrency',
  'Distributed Systems',
  'Event-Driven Architecture',
];
